### ISSUE TITLE
Exception in thread "pool-2521-thred-3" java.lang.ArrayIndexOutofBoundsException

### ISSUE THREAD

**Issue by EveTC** [tangyou79/LDkit#1]
Hello,

I am trying to run LDKit for my phased vcf (phased with ShapeIt v2).

Whislt running I recieve alot of the following exceptions:
```
Sun Jun 13 13:23:54 BST 2021   SUPER_5 chrom calculation number 1 Subgroup
Exception in thread "pool-1265-thread-1" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-6" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-3" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-12" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-13" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-15" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-11" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-22" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-21" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-29" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-16" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-24" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-26" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-19" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-39" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-47" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "pool-1265-thread-45" java.lang.ArrayIndexOutOfBoundsException
```

It happens for the majority of my subgroups. Is this something to worry about? I am running it with a thread of=32.

Thanks,
Eve

**Comment by mpage21** [comment]
I am also getting an exception similar to this.
`Exception in thread "pool-1-thread-1" java.lang.ArrayIndexOutOfBoundsException: Index 1000 out of bounds for length 1000
        at Comparison.VCFtoVCFThread.run(VCFtoVCFThread.java:250)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Mon Feb 20 23:37:19 UTC 2023   genotype readed
Mon Feb 20 23:37:19 UTC 2023   using 8 threads
Feb 20, 2023 11:37:19 PM main.mains main
SEVERE: null
java.lang.NullPointerException
        at ld.VcfTools.caThread(VcfTools.java:122)
        at ld.VcfTools.calCorall(VcfTools.java:156)
        at ld.LD.LD(LD.java:70)
        at main.mains.main(mains.java:116)
        at main.Format.Command(Format.java:183)
        at main.main.main(main.java:361)
`

Were you able to solve your error @EveTC ? 
@tangyou79 do you have any suggestions?
