### ISSUE TITLE
request help using LDkit

### ISSUE THREAD

**Issue by wbsimey** [tangyou79/LDkit#2]
Hello,
I have been unable to get LDkit to work for GUI or command line.
at the command line I am able to complete an LD analysis with:

`LDkit.jar --infile Neotoma_Chr26_2pops_HW.vcf.gz --out Neo_Chr26_LD --threads 32 --type 1`

but when I try to plot with:
` LDkit.jar --plot --inp Neo_Chr26_LD/result.txt.gz`

I get an error:
```
Exception in thread "main" java.lang.NullPointerException
        at plot.writeChartHtml.write(writeChartHtml.java:51)
        at plot.ReadResult.ReadResult(ReadResult.java:133)
        at plot.Plformat.Command(Plformat.java:49)
        at main.main.main(main.java:366)
```
What am I doing wrong?

My input data is a vcf from bcftool mpileup variant calling pipeline. It is one chromosome and 96 samples.

BTW, you have a typo in your description for using LDkit; you write "--output" instead of "--out"

**Comment by udiland** [comment]
Hi @wbsimey ,
Did you find a solution?

**Comment by r-poloni** [comment]
I answer just to point out that I have the same issue. I prefer using the command-line version because I already have all my data on a computing cluster, and I am not able to produce plots. When I launch the command:

java -jar LDkir.jar --plot --inp result.txt.gz 

I get the following error:

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "type" is null
        at plot.writeChartHtml.write(writeChartHtml.java:51)
        at plot.ReadResult.ReadResult(ReadResult.java:133)
        at plot.Plformat.Command(Plformat.java:49)
        at main.main.main(main.java:366)

I guess that the file to be used is this one just because with the other one I get an error telling me that LDkit wants a gzipped file, but I didn't find any instruction on how to build the plots and what file should I give.

**Comment by udiland** [comment]
I don't remember exactly how I solved this but I see that I changed the chromosome names to be only numbers

**Comment by r-poloni** [comment]
Hi! Thank you , I tried but it still gives the same error. In addition, if it was the error, it would have been a major bug since chromosome names frequently have non-integer characters.

**Comment by JoannaTan** [comment]
I cannot run the LD analysis. I passed in the ped,map file but it keeps giving me the follow error message
null
Please select the input file, you can select multiple, separated by commas
